name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-13 # Using macos-13 for Xcode 15 support

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'

      - name: Set Default Scheme
        run: |
          # Note: This assumes your main scheme is "FundMate"
          scheme="FundMate"
          echo $scheme | cat >default
          echo Using scheme: $scheme

      - name: Build
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          device="iPhone 15"
          if [ $scheme = default ]; then scheme=$(cat default); fi
          
          # Build for testing
          xcodebuild clean build-for-testing \
            -scheme "$scheme" \
            -project "FundMate.xcodeproj" \
            -destination "platform=iOS Simulator,name=$device" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Test
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          device="iPhone 15"
          if [ $scheme = default ]; then scheme=$(cat default); fi
          
          # Run tests
          xcodebuild test-without-building \
            -scheme "$scheme" \
            -project "FundMate.xcodeproj" \
            -destination "platform=iOS Simulator,name=$device" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
